{% set xorg_name = "xorgproto" %}
{% set xorg_category = "proto" %}
{% set name = "xorg-" ~ xorg_name %}
{% set version = "2022.1" %}
{% set sha256 = "1d2dcc66963f234d2c1e1f8d98a0d3e8725149cdac0a263df4097593c48bc2a6" %}
{% set am_version = "1.15" %} # keep synchronized with build.sh

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://www.x.org/releases/individual/{{ xorg_category }}/{{ xorg_name }}-{{ version }}.tar.bz2
  sha256: {{ sha256 }}
  patches:
    - 0001-windows-fds-bits.patch  # [win]

build:
  number: 0

requirements:
  build:
    - m2-autoconf  # [win]
    - m2-automake{{ am_version }}  # [win]
    - m2-libtool  # [win]
    - m2w64-pkg-config  # [win]
    - pkg-config  # [not win]
    - posix  # [win]
    - gnuconfig  # [unix]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - make  # [unix]
  host:
    - xorg-util-macros

test:
  commands:
    - test -e $PREFIX/include/X11/extensions/damageproto.h  # [not win]

about:
  home: https://www.x.org/
  license: MIT
  license_family: MIT
  license_file: licenses/
  summary: X.org protocol headers

extra:
  recipe-maintainers:
    - pkgw
